### ISSUE TITLE
Missing from Interactions Overview

### ISSUE THREAD

**Issue by LKocksch** [secure-software-engineering/rose#310] opened 2017-05-29 16:03 UTC
Some actions are tracked in the data storage but are not listed in the interactions overview: 

Open Link from Facebook

Write Private Message

**Comment by eppfel** [comment] 2017-05-30 15:41
Sry, where do you see this? Under data storage there is data?

I can not reproduce the error. And which observers  are you referring to? Write Private Message iis chat and open link from Facebook is ...?

**Comment by LKocksch** [comment] 2017-05-31 14:52
Under data storage I can find the event, however not in the interaction listing.

Private Message = Chat
Open link from Facebook = Klickin on a link on Facebook and thus opening a new window/tab

**Comment by eppfel** [comment] 2017-06-06 10:02
Can still not reproduce, because I cannot produce chat or "open-link" interactions at all. Guess chat is broken, but with open-link I don't realize which obesrver this should be.

@LKocksch Can you post the particular chat/open-link interactions from your data-management?

I will have another look into this, but I guess I have to fix the observers firts...

**Comment by LKocksch** [comment] 2017-06-07 16:25
Ok, sorry. I CANNOT find the chat event or view link in my data storage. I must have gotten the latter confused with reddit. Here, view link works just fine.

**Comment by eppfel** [comment] 2017-06-13 19:05
...sounds reasonable. Closing.

**Closed by eppfel** 2017-06-13 19:05 UTC
Labels: bug
