### ISSUE TITLE
New like options are recorded, but missing contentID and sharerID

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#251] opened 2016-03-27 16:22 UTC
The new like options interaction is recorded now after recent update. Thanks!

But the records for new like interactions are missing the "target" field that contains the contentID and sharerID. For example, in the screenshot, 9:17am and 9:00am were two new likes; 9:11am was a traditional like. Is this a deliberate choice or tech difficulties? 

This is not urgent, but if it's an easy fix, it would be nice to have those fields. If it's not an easy fix, we can leave without it. Thanks much!

<img width="508" alt="screen shot 2016-03-27 at 9 17 35 am" src="https://cloud.githubusercontent.com/assets/3218051/14066392/44e507f0-f3fd-11e5-9d4f-78ff342ccc96.png">

**Comment by iamolivinius** [comment] 2016-03-28 11:40
Unfortunately this isn't a easy one. I'll delay it until Felix is back at the office so we can discuss solutions for this.

**Comment by YiranWangPARC14** [comment] 2016-03-28 12:51
It's not a problem. Thank you!

**Comment by iamolivinius** [comment] 2016-03-31 16:07
Duplicate of: https://github.com/secure-software-engineering/rose/issues/247

**Closed by iamolivinius** 2016-03-31 16:07 UTC
