### ISSUE TITLE
New like options on FB

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#242] opened 2016-02-24 23:10 UTC
Now FB rolled out different options for the original like button. The original like observer is still working (I misspoke in the email). What is not working is when you hover the like button and use the new options, such as sad. In other words,  those like-varieties are not recorded.

**Comment by iamolivinius** [comment] 2016-02-28 21:09
Duplicate of #247

**Closed by iamolivinius** 2016-02-28 21:09 UTC
