### ISSUE TITLE
Firefox stops

### ISSUE THREAD

**Issue by LKocksch** [secure-software-engineering/rose#125] opened 2015-06-25 08:27 UTC
Firefox stops immediately after starting when ROSE 3.0 is enabled. Window popps up asking to restart or close Firefox. Windows 7.1, Firefox 38.0.5.. Thanks :)

**Comment by iamolivinius** [comment] 2015-06-25 10:30
I can confirm this bug. It's also present in the following setup: Linux/Firefox38

This is a really nasty problem because it keeps crashing even after restarting Firefox. Without commandline interaction one can not resolve this issue.

From an issue on kango's tracker one can conclude that we need to downgrade the kango runtime version to at least 1.7.1. https://github.com/KangoExtensions/kango/issues/126
Unfortunately there is no way right now to download previous versions of kango. See: http://kangoextensions.com/kango.html

**Comment by dharma-guardian** [comment] 2015-06-25 10:43
I can reproduce the error under OSX 10.10.3 / Firefox 38.0.5. I removed firefox from the release for now.

**Comment by apoller** [comment] 2015-06-25 11:36
I think you could ask the Kango developer for previous builds

**Comment by iamolivinius** [comment] 2015-06-26 16:10
Today's debugging results: FF SEGFAULTS! :fearful: 

First guess on what's causing this bug:

https://github.com/zloirock/core-js/issues/86 

Basically a harmless type error  in combination with kango crashes Firefox

**Comment by iamolivinius** [comment] 2015-07-03 01:28
https://bugzilla.mozilla.org/show_bug.cgi?id=1180075

**Comment by iamolivinius** [comment] 2015-07-07 08:29
FF doesn't crash in the actual version 39. Nevertheless ROSE won't run like expected.

**Comment by iamolivinius** [comment] 2015-07-10 15:30
Fixed in https://github.com/zloirock/core-js/commit/7985026cb9a57de54d98a02a0c6ee05c84ef2f33

**Closed by iamolivinius** 2015-07-10 15:30 UTC
Labels: bug, firefox
